excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://IT-Sumpfling.github.io
title: IT-Sumpfling
tagline: In den sumpfigen (Un-)Tiefen der IT - seit 1993
description: In den sumpfigen (Un-)Tiefen der IT - seit 1993
paginate: 5